# TCL File Generated by Component Editor 18.1
# Mon Mar 03 13:18:13 EST 2025
# DO NOT MODIFY


# 
# vhdl_servo_controller "vhdl_servo_controller" v1.0
# Andrew Akre 2025.03.03.13:18:13
# Server Controller
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vhdl_servo_controller
# 
set_module_property DESCRIPTION "Server Controller"
set_module_property NAME vhdl_servo_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ESDI_IP
set_module_property AUTHOR "Andrew Akre"
set_module_property DISPLAY_NAME vhdl_servo_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vhdl_servo_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vhdl_servo_controller.vhd VHDL PATH Custom_IP_Component/src/vhdl_servo_controller.vhd TOP_LEVEL_FILE
add_fileset_file angle_counter.vhd VHDL PATH Custom_IP_Component/src/angle_counter.vhd
add_fileset_file generic_counter.vhd VHDL PATH Custom_IP_Component/src/generic_counter.vhd
add_fileset_file state_machine_core.vhd VHDL PATH Custom_IP_Component/src/state_machine_core.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_1
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_o irq Output 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_1
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pwm_o writeresponsevalid_n Output 1


# 
# connection point clock_1
# 
add_interface clock_1 clock end
set_interface_property clock_1 clockRate 0
set_interface_property clock_1 ENABLED true
set_interface_property clock_1 EXPORT_OF ""
set_interface_property clock_1 PORT_NAME_MAP ""
set_interface_property clock_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_1 clk clk Input 1


# 
# connection point en_i_1
# 
add_interface en_i_1 avalon end
set_interface_property en_i_1 addressUnits WORDS
set_interface_property en_i_1 associatedClock clock_1
set_interface_property en_i_1 associatedReset reset
set_interface_property en_i_1 bitsPerSymbol 8
set_interface_property en_i_1 burstOnBurstBoundariesOnly false
set_interface_property en_i_1 burstcountUnits WORDS
set_interface_property en_i_1 explicitAddressSpan 0
set_interface_property en_i_1 holdTime 0
set_interface_property en_i_1 linewrapBursts false
set_interface_property en_i_1 maximumPendingReadTransactions 0
set_interface_property en_i_1 maximumPendingWriteTransactions 0
set_interface_property en_i_1 readLatency 0
set_interface_property en_i_1 readWaitTime 1
set_interface_property en_i_1 setupTime 0
set_interface_property en_i_1 timingUnits Cycles
set_interface_property en_i_1 writeWaitTime 0
set_interface_property en_i_1 ENABLED true
set_interface_property en_i_1 EXPORT_OF ""
set_interface_property en_i_1 PORT_NAME_MAP ""
set_interface_property en_i_1 CMSIS_SVD_VARIABLES ""
set_interface_property en_i_1 SVD_ADDRESS_GROUP ""

add_interface_port en_i_1 write_en_i write Input 1
add_interface_port en_i_1 write_data_i writedata Input 32
add_interface_port en_i_1 addr_i address Input 1
set_interface_assignment en_i_1 embeddedsw.configuration.isFlash 0
set_interface_assignment en_i_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment en_i_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment en_i_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_1
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_i reset_n Input 1

